# Languages
#   Create a section for each of your site's languages.
#   Documentation: https://docs.hugoblox.com/reference/language/

# Default language
en:
  label: English
  locale: en-us
  weight: 1

# Russian version
ru:
  label: Русский
  locale: ru-ru
  weight: 2
  params:
    description: Персональный сайт Кирилла Челухаева, студента направления
      «Прикладная информатика» РУДН.
    hugoblox:
      identity:
        name: 'Кирилл Челухаев'
  menu:
    main:
      - name: Обо мне
        url: /
        weight: 10
      - name: Посты
        url: blog/
        weight: 20
      - name: Опыт
        url: experience/
        weight: 30
      - name: Проекты
        url: projects/
        weight: 40
